// SPDX-FileCopyrightText: Copyright Balance Hormone Center and Plumb contributors
// SPDX-License-Identifier: Apache-2.0

// Print: every formatting rule lives here. A pure function from the type
// model to text, with no FHIR knowledge.
import { FileBuilder, wordWrap } from '@medplum/core';
import type { Route, Routing } from './routes.js';
import type { Field, Helper, ProfileModel, TypeExpr } from './transform.js';

/** The first line of every file Plumb writes, so it can tell its files from others. */
export const MARKER = '// Generated by Plumb';
const WIDTH = 100;

const HELPERS = `${MARKER}. Do not edit.
/** \`T\` with the keys \`K\` required, and never \`undefined\`. */
export type Require<T, K extends keyof T> = Omit<T, K> & { [P in K]-?: NonNullable<T[P]> };

/** \`Omit\` over each member of a union, so an exactly-one-of type stays one. */
export type OmitEach<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never;

/**
 * Whether \`value\` holds everything in \`pattern\`, as FHIR matches a slice's
 * discriminator: an array in the pattern means each entry appears somewhere, and
 * a single pattern against an array is met by any entry.
 */
export function matches(value: unknown, pattern: unknown): boolean {
  if (Array.isArray(value) && !Array.isArray(pattern)) return value.some((v) => matches(v, pattern));
  if (Array.isArray(pattern)) {
    return Array.isArray(value) && pattern.every((p) => value.some((v) => matches(v, p)));
  }
  if (pattern !== null && typeof pattern === 'object') {
    if (value === null || typeof value !== 'object') return false;
    const record = value as Record<string, unknown>;
    return Object.entries(pattern).every(([key, p]) => matches(record[key], p));
  }
  return value === pattern;
}

/**
 * The rows of a \`required\` table (_reads.ts) a resource does not meet. A row
 * lists alternatives, any one of which meets it. A nested path applies to every
 * entry present, a number to one entry, and \`key*\` to \`key\` at any depth.
 */
export function missing(resource: object, rows: readonly (readonly string[])[]): string[] {
  return rows.filter((row) => !meets(resource, row)).map((row) => row.join(' | '));
}

/** Whether every entry at the row's parent path holds one of its alternatives. */
function meets(resource: object, row: readonly string[]): boolean {
  let nodes: unknown[] = [resource];
  for (const key of (row[0] ?? '').split('.').slice(0, -1)) {
    nodes = key.endsWith('*') ? deep(nodes, key.slice(0, -1)) : nodes.flatMap((n) => step(n, key));
  }
  const keys = row.map((path) => path.slice(path.lastIndexOf('.') + 1));
  return nodes.flat().every((node) => keys.some((key) => step(node, key).length > 0));
}

/** The values present at \`key\`: in each entry of an array, or one entry by its index. */
function step(node: unknown, key: string): unknown[] {
  if (Array.isArray(node)) {
    return /^\\d+$/.test(key) ? node.slice(Number(key), Number(key) + 1) : node.flatMap((n) => step(n, key));
  }
  const value = node !== null && typeof node === 'object' ? (node as Record<string, unknown>)[key] : undefined;
  return value === undefined || value === null ? [] : [value];
}

/** The nodes, and what \`key\` reaches from them at every depth. */
function deep(nodes: unknown[], key: string): unknown[] {
  const all: unknown[] = [];
  for (let level = nodes; level.length > 0; level = level.flatMap((n) => step(n, key))) all.push(...level);
  return all;
}
`;

// Only with Questionnaires in content, so a project without any has no unused export.
const ANSWERS = `
import type { QuestionnaireResponse, QuestionnaireResponseItem } from '@medplum/fhirtypes';

/**
 * A response's answers by linkId, through groups and items nested under
 * answers, as @medplum/core's getQuestionnaireAnswers reads them: the first
 * answer's value, or every one for an item in \`repeats\`.
 */
export function readAnswers(
  response: QuestionnaireResponse,
  url: string,
  repeats: readonly string[],
): Record<string, unknown> {
  const answered = response.questionnaire?.split('|')[0];
  if (answered !== url) throw new Error(\`The response answers \${answered ?? 'no Questionnaire'}, not \${url}.\`);
  const answers: Record<string, unknown> = {};
  const walk = (items: QuestionnaireResponseItem[] = []): void => {
    for (const item of items) {
      for (const answer of item.answer ?? []) {
        const key = Object.keys(answer).find((k) => k.startsWith('value'));
        const value = key ? (answer as Record<string, unknown>)[key] : undefined;
        if (value !== undefined && repeats.includes(item.linkId)) {
          answers[item.linkId] = [...((answers[item.linkId] as unknown[]) ?? []), value];
        } else if (value !== undefined && !(item.linkId in answers)) {
          answers[item.linkId] = value;
        }
        walk(answer.item);
      }
      walk(item.item);
    }
  };
  walk(response.item);
  return answers;
}
`;

/**
 * Operation contracts, written only when the config lists `operations`. A file
 * of its own, since it reads profiles with `asProfiled` from _reads.ts, which
 * itself imports _plumb.ts.
 */
const OPERATIONS = `${MARKER}. Do not edit.
import type { OperationOutcome, OperationOutcomeIssue, Parameters, Resource, ResourceType } from '@medplum/fhirtypes';
import { asProfiled } from './_reads.js';
import type { ProfileTypes, ProfileUrl } from './_routes.js';

/** The Standard Schema interface (standardschema.dev), which Zod, Valibot, ArkType and others implement. */
export interface StandardSchemaV1<Input = unknown, Output = Input> {
  readonly '~standard': {
    readonly version: 1;
    readonly vendor: string;
    readonly validate: (value: unknown) => StandardResult<Output> | Promise<StandardResult<Output>>;
    readonly types?: { readonly input: Input; readonly output: Output } | undefined;
  };
}

type StandardResult<Output> =
  | { readonly value: Output; readonly issues?: undefined }
  | { readonly issues: readonly StandardIssue[] };

interface StandardIssue {
  readonly message: string;
  readonly path?: readonly (PropertyKey | { readonly key: PropertyKey })[] | undefined;
}

/** One side of an operation: a resource type, a selected profile, or a Standard Schema for plain JSON. */
export type OperationSide = ResourceType | ProfileUrl | StandardSchemaV1;

type FhirType<S> = S extends ProfileUrl
  ? ProfileTypes[S]
  : S extends ResourceType
    ? Extract<Resource, { resourceType: S }>
    : never;

/** What a side takes: a schema's input, or the FHIR type. */
export type SideInput<S> = S extends StandardSchemaV1 ? NonNullable<S['~standard']['types']>['input'] : FhirType<S>;

/** What a side gives once checked: a schema's output, or the FHIR type. */
export type SideOutput<S> = S extends StandardSchemaV1 ? NonNullable<S['~standard']['types']>['output'] : FhirType<S>;

// TypeScript 5.4's NoInfer, for the 5.0 the generated code supports: a side is
// fixed by the contract, never inferred from a caller's input or a handler's return.
type Fixed<T> = [T][T extends unknown ? 0 : never];

/** A custom operation, implemented by a bot: what it takes and what it returns. */
export interface OperationContract<I extends OperationSide = OperationSide, O extends OperationSide = OperationSide> {
  /** Called as \`$code\`. */
  code: string;
  level: 'system' | 'type' | 'instance';
  /** The resource type a type or instance operation is on. */
  resource?: ResourceType;
  /** The key in \`bots\` of the bot that implements it. */
  bot: string;
  input: I;
  output: O;
}

/** Types a contract; returns it unchanged. */
export function defineOperation<const I extends OperationSide, const O extends OperationSide>(
  contract: OperationContract<I, O>,
): OperationContract<I, O> {
  return contract;
}

/** An operation's failed check, here or in the bot, with the OperationOutcome that says why. */
export class OperationError extends Error {
  readonly outcome: OperationOutcome;
  constructor(code: string, outcome: OperationOutcome) {
    const reasons = outcome.issue.map((i) => i.details?.text ?? i.diagnostics ?? i.code);
    super(\`$\${code}: \${reasons.join('; ')}\`);
    this.name = 'OperationError';
    this.outcome = outcome;
  }
}

/**
 * What \`callOperation\` needs of a client: a MedplumClient fits. Typed
 * without \`URL\`, so a project needs neither the DOM lib nor @types/node.
 */
export interface OperationClient {
  fhirUrl(...path: string[]): { toString(): string };
  post(url: string, body: unknown, contentType?: string): Promise<unknown>;
}

/**
 * Calls an operation: checks the input, POSTs it as is, and checks what comes
 * back. A failed check, or the server's refusal, throws an OperationError.
 * An instance operation runs on \`options.id\`, or the input's own id.
 */
export async function callOperation<I extends OperationSide, O extends OperationSide>(
  medplum: OperationClient,
  operation: OperationContract<I, O>,
  input: SideInput<Fixed<I>>,
  options: { id?: string } = {},
): Promise<SideOutput<O>> {
  await checked(operation.code, operation.input, 'input', input);
  const id = options.id ?? (input as { id?: string } | undefined)?.id ?? '';
  const path =
    operation.level === 'system'
      ? []
      : operation.level === 'type'
        ? [operation.resource ?? '']
        : [operation.resource ?? '', id];
  const json = typeof operation.input === 'object';
  let response: unknown;
  try {
    response = await medplum.post(
      medplum.fhirUrl(...path, \`$\${operation.code}\`).toString(),
      input,
      json ? 'application/json' : 'application/fhir+json',
    );
  } catch (err) {
    const outcome = (err as { outcome?: OperationOutcome } | undefined)?.outcome;
    if (outcome?.resourceType === 'OperationOutcome') throw new OperationError(operation.code, outcome);
    throw err;
  }
  return checked(operation.code, operation.output, 'output', unwrap(response));
}

/**
 * A bot's handler for an operation: the input is checked before \`handler\`
 * runs, and its return before it goes back. A resource is returned as is,
 * which Medplum sends back through the \`return\` out parameter; JSON as
 * \`{ result }\`, a string Medplum maps to the \`result\` out parameter, as
 * every release does. A failed check throws, which Medplum answers with a 400.
 */
export function handleOperation<I extends OperationSide, O extends OperationSide, Client>(
  operation: OperationContract<I, O>,
  handler: (
    medplum: Client,
    input: SideOutput<Fixed<I>>,
  ) => SideInput<Fixed<O>> | Promise<SideInput<Fixed<O>>>,
): (medplum: Client, event: { input: unknown }) => Promise<Resource | { result: string }> {
  return async (medplum, event) => {
    const input = await checked(operation.code, operation.input, 'input', event.input);
    const output = await handler(medplum, input as SideOutput<Fixed<I>>);
    await checked(operation.code, operation.output, 'output', output);
    // The handler's own value, not the schema's output, so the caller's check reads it as written.
    return typeof operation.output === 'object'
      ? { result: JSON.stringify(output) }
      : (output as Resource);
  };
}

/** A side's checked value, or an OperationError naming each issue. */
async function checked<S extends OperationSide>(
  code: string,
  side: S,
  which: 'input' | 'output',
  value: unknown,
): Promise<SideOutput<S>> {
  const issues = await problems(side, value);
  if ('value' in issues) return issues.value as SideOutput<S>;
  throw new OperationError(code, {
    resourceType: 'OperationOutcome',
    issue: issues.problems.map((text): OperationOutcomeIssue => ({
      severity: 'error',
      code: 'invalid',
      details: { text: \`\${which}\${text}\` },
    })),
  });
}

async function problems(side: OperationSide, value: unknown): Promise<{ value: unknown } | { problems: string[] }> {
  if (typeof side === 'object') {
    const result = await side['~standard'].validate(value);
    if (!result.issues) return { value: result.value };
    return { problems: result.issues.map((i) => \`\${pathOf(i.path)}: \${i.message}\`) };
  }
  const resource = value as Resource | undefined;
  // A profile is named by its canonical URL; a resource type never holds a ':'.
  if (side.includes(':')) {
    try {
      return { value: asProfiled(resource as Resource, side as ProfileUrl) };
    } catch (err) {
      return { problems: [\`: \${(err as Error).message}\`] };
    }
  }
  return resource?.resourceType === side
    ? { value: resource }
    : { problems: [\`: expected a \${side}, not \${resource?.resourceType ?? typeof value}\`] };
}

const pathOf = (path: StandardIssue['path']) =>
  (path ?? [])
    .map((p) => (typeof p === 'object' ? p.key : p))
    .map((key) => (typeof key === 'number' ? \`[\${key}]\` : \`.\${String(key)}\`))
    .join('');

/** A \`Parameters\` response's \`return\` resource, or its \`result\` string read as JSON. */
function unwrap(response: unknown): unknown {
  const parameters = response as Parameters | undefined;
  if (parameters?.resourceType !== 'Parameters') return response;
  const parameter = parameters.parameter?.find((p) => p.name === 'return' || p.name === 'result');
  return parameter?.name === 'result' ? JSON.parse(parameter.valueString ?? 'null') : parameter?.resource;
}
`;

export const quote = (text: string) => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const indentRest = (text: string, by: string) => text.replaceAll('\n', `\n${by}`);
const needsParens = (t: TypeExpr) => t.kind === 'union' || t.kind === 'narrow';
const paren = (t: TypeExpr) => (needsParens(t) ? `(${printExpr(t)})` : printExpr(t));

function docLines(text: string[], width: number): string[] {
  const body = text.flatMap((line) =>
    line ? wordWrap(line.replaceAll('*/', '*\\/'), width) : [''],
  );
  return ['/**', ...body.map((line) => (line ? ` * ${line}` : ' *')), ' */'];
}

function printField(field: Field): string {
  const line = `${field.name}${field.optional ? '?' : ''}: ${printExpr(field.type)};`;
  if (!field.doc) return line;
  const doc = `/** ${field.doc.replaceAll('*/', '*\\/')} */`;
  const lines = doc.length <= WIDTH - 2 ? [doc] : docLines([field.doc], WIDTH - 5);
  return [...lines, line].join('\n');
}

function block(fields: Field[]): string {
  if (fields.length === 0) return '{}';
  return `{\n${fields.map((f) => `  ${indentRest(printField(f), '  ')}`).join('\n')}\n}`;
}

/** Joins keys with ' | ' into lines no wider than `width`. */
function fill(keys: string[], width: number): string[] {
  const lines: string[] = [];
  for (const key of keys) {
    const last = lines.at(-1);
    if (last !== undefined && last.length + key.length + 3 <= width)
      lines[lines.length - 1] = `${last} | ${key}`;
    else lines.push(key);
  }
  return lines;
}

/** A type expression as TypeScript; nested lines are indented relative to the first. */
export function printExpr(t: TypeExpr): string {
  switch (t.kind) {
    case 'ref':
      return t.args ? `${t.name}<${t.args.map(printExpr).join(', ')}>` : t.name;
    case 'primitive':
      return t.name;
    case 'index':
      return `NonNullable<${t.base}[${quote(t.key)}]>`;
    case 'literal':
      return typeof t.value === 'string' ? quote(t.value) : String(t.value);
    case 'array':
      return `${paren(t.of)}[]`;
    case 'tuple':
      return `[${t.of.map(printExpr).join(', ')}]`;
    case 'optional':
      return `${paren(t.of)}?`;
    case 'rest':
      return `...${paren(t.of)}[]`;
    case 'union':
      return t.of.map(paren).join(' | ');
    case 'object':
      return block(t.fields);
    case 'require':
      return `Require<${printExpr(t.base)}, ${t.keys.map(quote).join(' | ')}>`;
    case 'never':
      return 'never';
    case 'otherString':
      return '(string & {})';
    case 'narrow': {
      const base = printExpr(t.base);
      const keys = t.omit.map(quote);
      const inline = `Omit<${base}, ${keys.join(' | ')}>`;
      // A long list goes one key per line, so the file stays readable.
      const omitted =
        keys.length === 0
          ? base
          : inline.length <= 80
            ? inline
            : `Omit<\n  ${base},\n${fill(keys, WIDTH - 4)
                .map((line) => `  | ${line}`)
                .join('\n')}\n>`;
      const groups = (t.oneOf ?? []).map(
        (branches) =>
          ` & (\n${branches.map((b) => `  | ${indentRest(block(b), '    ')}`).join('\n')}\n)`,
      );
      return `${omitted} & ${block(t.fields)}${groups.join('')}`;
    }
  }
}

/** Every type name an expression refers to. */
function names(t: TypeExpr, into: Set<string>): Set<string> {
  switch (t.kind) {
    case 'ref':
      into.add(t.name);
      for (const arg of t.args ?? []) names(arg, into);
      break;
    case 'index':
      into.add(t.base);
      break;
    case 'array':
    case 'optional':
    case 'rest':
      names(t.of, into);
      break;
    case 'tuple':
    case 'union':
      for (const item of t.of) names(item, into);
      break;
    case 'object':
      for (const f of t.fields) names(f.type, into);
      break;
    case 'require':
      into.add('Require');
      names(t.base, into);
      break;
    case 'narrow':
      names(t.base, into);
      for (const f of [...t.fields, ...(t.oneOf ?? []).flat(2)]) names(f.type, into);
      break;
  }
  return into;
}

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

/** A JSON value as a TypeScript expression. */
function printValue(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(printValue).join(', ')}]`;
  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value).map(
      ([key, v]) => `${IDENTIFIER.test(key) ? key : quote(key)}: ${printValue(v)}`,
    );
    return `{ ${entries.join(', ')} }`;
  }
  return typeof value === 'string' ? quote(value) : String(value);
}

function printHelper(h: Helper): string[] {
  const keys = Object.keys(h.values);
  if (h.kind === 'build') {
    return [
      `  /** ${/^[aeiou]/i.test(h.element) ? 'An' : 'A'} ${h.element} entry in the ${h.slice} slice, with ${keys.join(' and ')} filled in. */`,
      `  ${h.name}: (entry: OmitEach<${h.shape}, ${keys.map(quote).join(' | ')}>): ${h.shape} => ({`,
      '    ...entry,',
      ...keys.map((key) => `    ${key}: ${printValue(h.values[key])},`),
      '  }),',
    ];
  }
  return [
    `  /** The first ${h.element} entry in the ${h.slice} slice, if there is one. */`,
    `  ${h.name}: (parent: { ${h.element}?: ${h.item}[] }): ${h.shape} | undefined =>`,
    `    parent.${h.element}?.find((e): e is ${h.shape} => matches(e, ${printValue(h.values)})),`,
  ];
}

/** Which file declares each generated type, so a file can import another's. */
type Owners = Map<string, string>;

function printProfile(model: ProfileModel, hash: string, owners: Owners): string {
  const b = new FileBuilder('  ', false);
  const version = model.version ? `|${model.version}` : '';
  b.appendNoWrap(`${MARKER} from ${model.url}${version}. Do not edit.`);
  b.appendNoWrap(`// Source: ${model.source} ${hash}`);
  const used = new Set<string>();
  for (const d of model.decls) names(d.type, used);
  for (const h of model.helpers) used.add(h.item);
  const local = new Set(model.decls.map((d) => d.name));
  const foreign = [...used].filter((n) => !local.has(n) && n !== 'Require');
  const fhir = foreign.filter((n) => !owners.has(n)).sort();
  if (fhir.length > 0)
    b.appendNoWrap(`import type { ${fhir.join(', ')} } from '@medplum/fhirtypes';`);
  const files = [...new Set(foreign.flatMap((n) => owners.get(n) ?? []))].sort();
  for (const file of files) {
    const names = foreign.filter((n) => owners.get(n) === file).sort();
    b.appendNoWrap(`import type { ${names.join(', ')} } from './${file}.js';`);
  }
  const plumb = [
    ...(model.helpers.length > 0 ? ['matches'] : []),
    ...(model.helpers.some((h) => h.kind === 'build') ? ['type OmitEach'] : []),
    ...(used.has('Require') ? ['type Require'] : []),
  ];
  if (plumb.length > 0) b.appendNoWrap(`import { ${plumb.join(', ')} } from './_plumb.js';`);
  b.newLine();
  b.appendNoWrap(`/** The canonical URL of ${model.typeName}. */`);
  b.appendNoWrap(`export const ${model.typeName}ProfileUrl = ${quote(model.url)};`);
  for (const constant of model.constants) {
    b.newLine();
    b.appendNoWrap(`/** The codes of ${constant.name.slice(0, -'Codes'.length)}. */`);
    b.appendNoWrap(`export const ${constant.name} = [`);
    for (const c of constant.codes) b.appendNoWrap(`  ${printValue(c)},`);
    b.appendNoWrap('] as const;');
  }
  model.decls.forEach((d, i) => {
    b.newLine();
    if (i === 0) for (const line of docLines(model.doc, WIDTH - 3)) b.appendNoWrap(line);
    for (const line of `export type ${d.name} = ${printExpr(d.type)};`.split('\n'))
      b.appendNoWrap(line);
  });
  if (model.helpers.length > 0) {
    b.newLine();
    b.appendNoWrap(`/** Builders and readers for the slices of ${model.typeName}. */`);
    b.appendNoWrap(`export const ${model.typeName} = {`);
    for (const line of model.helpers.flatMap(printHelper)) b.appendNoWrap(line);
    b.appendNoWrap('};');
  }
  return b.toString();
}

const ROUTE = `interface Row {
  readonly profile: ProfileUrl;
  readonly parents: readonly string[];
  readonly keys: readonly (readonly [string, readonly unknown[]])[];
}

/** Thrown when no selected profile, or several unrelated ones, match a resource. */
export class RoutingError extends Error {
  /** The profiles that matched, or every routed profile on the type when none did. */
  readonly candidates: readonly ProfileUrl[];
  constructor(message: string, candidates: readonly ProfileUrl[]) {
    super(message);
    this.name = 'RoutingError';
    this.candidates = candidates;
  }
}

/**
 * The selected profile a resource's content selects: every row whose keys all
 * match, less any that is a parent of another match. \`undefined\` when no
 * selected profile constrains the resource's type. Throws a RoutingError when
 * none, or several unrelated ones, match: it never guesses.
 */
export function route(resource: Resource): ProfileUrl | undefined {
  const table: Partial<Record<string, readonly Row[]>> = routes;
  const rows = table[resource.resourceType];
  if (!rows) return undefined;
  const fields = resource as unknown as Record<string, unknown>;
  const matched = rows.filter((row) =>
    row.keys.every(([element, patterns]) => patterns.some((p) => matches(fields[element], p))),
  );
  const best = matched.filter((row) => !matched.some((other) => other.parents.includes(row.profile)));
  if (best.length === 1) return best[0]?.profile;
  const type = resource.resourceType;
  const shown = best.length === 0 ? rows : best;
  const width = Math.max(0, ...shown.map((row) => short(row.profile).length));
  throw new RoutingError(
    [
      best.length === 0
        ? \`no profile matches this \${type}.\`
        : \`\${best.length} unrelated profiles match this \${type}.\`,
      ...shown.map((row) => \`  \${short(row.profile).padEnd(width)}   \${needs(row, type)}\`),
      'Pass { profile } to choose one, or { profile: false } to write it unprofiled.',
    ].join('\\n'),
    shown.map((row) => row.profile),
  );
}

const short = (url: string) => url.slice(url.lastIndexOf('/') + 1);

function needs(row: Row, type: string): string {
  if (row.keys.length === 0) return \`matches any \${type}\`;
  return \`needs \${row.keys.map(([element, patterns]) => \`\${element} \${patterns.map(describe).join(' or ')}\`).join(', ')}\`;
}

/** A pattern as a reader would say it: a coding as system|code, an object by its fields. */
function describe(pattern: unknown): string {
  if (typeof pattern !== 'object' || pattern === null) return String(pattern);
  const { system, code, coding } = pattern as { system?: unknown; code?: unknown; coding?: unknown };
  if (Array.isArray(coding)) return coding.map(describe).join(' and ');
  if (typeof code === 'string' && Object.keys(pattern).every((k) => ['system', 'code', 'display'].includes(k))) {
    return typeof system === 'string' ? \`\${system}|\${code}\` : code;
  }
  return Object.entries(pattern)
    .map(([key, value]) => \`\${key} \${describe(value)}\`)
    .join(', ');
}
`;

const WRITE = `/**
 * The part of a \`MedplumClient\` the writes use, so the generated code needs no
 * \`@medplum/core\` declarations of its own: a MedplumClient is one.
 */
export interface ProfiledClient {
  createResource<T extends Resource>(resource: T): Promise<T>;
  updateResource<T extends Resource>(resource: T): Promise<T>;
}

/** What a write to each selected profile stamps: the type's defaults it does not derive from, then the profile. */
const stamps: Record<ProfileUrl, readonly string[]> = STAMPS;

/** Every URL Plumb stamps. A write replaces these in \`meta.profile\`, and keeps any other. */
const managed: ReadonlySet<string> = new Set<string>(MANAGED);

/**
 * A copy of the resource stamped for the profile: the URLs Plumb does not
 * manage, then the profile's stamps. With no profile, only the other URLs
 * stay, and an empty \`meta.profile\` is left out: it would skip the server's
 * \`defaultProfile\`.
 */
function stamped<T extends Resource>(resource: T, profile: ProfileUrl | false | undefined): T {
  const { profile: current = [], ...meta } = resource.meta ?? {};
  const kept = current.filter((url) => !managed.has(url.split('|')[0] ?? url));
  const profiles = [...kept, ...(profile ? stamps[profile] : [])];
  const { meta: _, ...rest } = resource;
  if (profiles.length > 0) return { ...rest, meta: { ...meta, profile: profiles } } as T;
  return (Object.keys(meta).length > 0 ? { ...rest, meta } : rest) as T;
}

/**
 * Creates the resource held to the profile its content selects, stamped with
 * that profile and the project's defaults. \`{ profile }\` chooses one instead,
 * and \`{ profile: false }\` writes it with no Plumb stamp, so the server's own
 * default applies. Rejects with a RoutingError, before anything is written,
 * when the content selects no single profile. The resource passed is not changed.
 */
export function createProfiled<U extends ProfileUrl>(
  medplum: ProfiledClient,
  resource: ProfileTypes[U],
  options: { profile: U },
): Promise<ProfileTypes[U]>;
export function createProfiled<T extends Resource>(
  medplum: ProfiledClient,
  resource: T,
  options?: { profile: false },
): Promise<T>;
export async function createProfiled(
  medplum: ProfiledClient,
  resource: Resource,
  options: { profile?: ProfileUrl | false } = {},
): Promise<Resource> {
  return medplum.createResource(stamped(resource, options.profile ?? route(resource)));
}

declare const plumbStamped: unique symbol;

/**
 * What stampProfiled returns carries this, so \`plumb check\` can tell a stamped
 * write from a raw one, through a variable too. Optional, so it asks nothing of
 * a caller and changes nothing it can assign.
 */
type Stamped = { readonly [plumbStamped]?: true };

/**
 * The copy createProfiled would write, stamped and not written, for the writes
 * it cannot make: a conditional create, an upsert, a batch or transaction
 * entry. Options and errors as createProfiled; a RoutingError is thrown.
 */
export function stampProfiled<U extends ProfileUrl>(
  resource: ProfileTypes[U],
  options: { profile: U },
): ProfileTypes[U] & Stamped;
export function stampProfiled<T extends Resource>(
  resource: T,
  options?: { profile: false },
): T & Stamped;
export function stampProfiled(
  resource: Resource,
  options: { profile?: ProfileUrl | false } = {},
): Resource {
  return stamped(resource, options.profile ?? route(resource));
}

/**
 * Updates the resource held to the profile its new content selects: the
 * stamps Plumb manages are replaced, and any other URL in \`meta.profile\` is
 * kept. Options and errors as createProfiled.
 */
export function updateProfiled<U extends ProfileUrl>(
  medplum: ProfiledClient,
  resource: ProfileTypes[U],
  options: { profile: U },
): Promise<ProfileTypes[U]>;
export function updateProfiled<T extends Resource>(
  medplum: ProfiledClient,
  resource: T,
  options?: { profile: false },
): Promise<T>;
export async function updateProfiled(
  medplum: ProfiledClient,
  resource: Resource,
  options: { profile?: ProfileUrl | false } = {},
): Promise<Resource> {
  return medplum.updateResource(stamped(resource, options.profile ?? route(resource)));
}
`;

/**
 * The routing rows, by resource type then profile URL so a profile change
 * moves only its own lines, with the selected profiles' types and `route`.
 */
function printRoutes(routing: RoutingTable, typeNames: Map<string, string>): string {
  const selected = routing.profiles
    .flatMap((url) => {
      const name = typeNames.get(url);
      return name ? [[url, name] as const] : [];
    })
    .sort(([a], [b]) => a.localeCompare(b));
  const lines = [`${MARKER}. Do not edit.`, "import type { Resource } from '@medplum/fhirtypes';"];
  lines.push("import { matches } from './_plumb.js';");
  for (const name of [...new Set(selected.map(([, n]) => n))].sort()) {
    lines.push(`import type { ${name} } from './${name}.js';`);
  }
  lines.push('', "/** Each selected profile's type, by canonical URL. */");
  if (selected.length === 0) lines.push('export type ProfileTypes = {};');
  else {
    lines.push('export type ProfileTypes = {');
    for (const [url, name] of selected) lines.push(`  ${quote(url)}: ${name};`);
    lines.push('};');
  }
  lines.push(
    '',
    '/** The canonical URL of a selected profile. */',
    'export type ProfileUrl = keyof ProfileTypes;',
    '',
    '/**',
    ' * The content that selects each profile: a row matches a resource when, for',
    ' * every key, the element holds one of its patterns (`matches` in _plumb.ts).',
    ' */',
    'const routes = {',
    ...Object.keys(routing.routes)
      .sort()
      .flatMap((type) => printRows(type, routing.routes[type] ?? [])),
    '} as const;',
    '',
    ROUTE,
    WRITE.replace('STAMPS', printStamps(routing.stamps)).replace(
      'MANAGED',
      printValue([...routing.managed].sort()),
    ),
  );
  return lines.join('\n');
}

function printRows(type: string, routes: Route[]): string[] {
  if (routes.length === 0) return [`  ${type}: [],`];
  const rows = [...routes].sort((a, b) => a.profile.localeCompare(b.profile));
  return [
    `  ${type}: [`,
    ...rows.flatMap((row) => [
      '    {',
      `      profile: ${quote(row.profile)},`,
      `      parents: ${printValue(row.parents)},`,
      ...(row.keys.length === 0
        ? ['      keys: [],']
        : ['      keys: [', ...row.keys.map((key) => `        ${printValue(key)},`), '      ],']),
      '    },',
    ]),
    '  ],',
  ];
}

type RoutingTable = Pick<Routing, 'routes' | 'profiles' | 'stamps' | 'managed' | 'accepts'>;

const READS = `/** A record that failed a read, and the paths it lacks. */
export interface ProfileReadFailure {
  readonly reference: string;
  readonly missing: readonly string[];
}

/**
 * Thrown when a resource read as a profile is not stamped with it, lacks what
 * its type requires, or was asked for in a way that cannot hold the type. The
 * message names records and paths, never their values.
 */
export class ProfileReadError<U extends ProfileUrl = ProfileUrl> extends Error {
  readonly profile: U;
  readonly reason: 'unstamped' | 'missing' | 'refused';
  readonly failed: readonly ProfileReadFailure[];
  /**
   * The records that passed, typed once \`ProfileReadError.is\` narrows the error.
   * Not enumerable: loggers and error trackers copy an error's enumerable
   * properties into their reports, and these hold clinical data.
   */
  declare readonly passed: readonly ProfileTypes[U][];

  constructor(
    profile: U,
    reason: 'unstamped' | 'missing' | 'refused',
    failed: readonly ProfileReadFailure[],
    passed: readonly ProfileTypes[U][] = [],
    message = describe(profile, reason, failed),
  ) {
    super(message);
    this.name = 'ProfileReadError';
    this.profile = profile;
    this.reason = reason;
    this.failed = failed;
    Object.defineProperty(this, 'passed', { value: passed, enumerable: false });
  }

  /** Whether \`err\` is a ProfileReadError for the profile, which types its \`passed\`. */
  static is<U extends ProfileUrl>(err: unknown, profile: U): err is ProfileReadError<U> {
    return err instanceof ProfileReadError && err.profile === profile;
  }
}

const short = (url: string) => url.slice(url.lastIndexOf('/') + 1);

function describe(profile: ProfileUrl, reason: string, failed: readonly ProfileReadFailure[]): string {
  const name = short(profile);
  const [first] = failed;
  if (reason === 'unstamped' && first) {
    return [
      \`\${first.reference} is not a \${name}.\`,
      \`  unstamped  meta.profile holds neither \${name} nor a selected profile deriving from it.\`,
    ].join('\\n');
  }
  const width = Math.max(0, ...failed.map((f) => f.reference.length));
  return [
    failed.length === 1 && first ? \`\${first.reference} is not a \${name}.\` : \`\${failed.length} records are not a \${name}.\`,
    ...(failed.length === 1
      ? (first?.missing ?? []).map((path) => \`  missing  \${path}\`)
      : failed.map((f) => \`  \${f.reference.padEnd(width)}   missing  \${f.missing.join(', ')}\`)),
    'Stamped records lack required data when written while the project was loose,',
    'when an AccessPolicy hides the field, or when the profile tightened since.',
    'See \`plumb validate --env <env>\`.',
  ].join('\\n');
}

/** Whether \`meta.profile\` holds the profile's bare URL, or a selected profile deriving from it. */
function stampedAs(resource: Resource, profile: ProfileUrl): boolean {
  return resource.meta?.profile?.some((url) => accepts[profile]?.includes(url)) ?? false;
}

const referenceOf = (resource: Resource) =>
  resource.id ? \`\${resource.resourceType}/\${resource.id}\` : \`\${resource.resourceType} with no id\`;

/** The rows of the profile's \`required\` the resource lacks, as paths from its type. */
const lacks = (resource: Resource, profile: ProfileUrl) =>
  missing(resource, required[profile]).map((path) => \`\${resource.resourceType}.\${path}\`);

/**
 * Whether the resource is the profile's: stamped with it or a selected profile
 * deriving from it, and holding every path its type requires. Pure and offline;
 * asProfiled, pickProfiled and the reads all run this check.
 */
export function isProfiled<U extends ProfileUrl>(resource: Resource, profile: U): resource is Resource & ProfileTypes[U] {
  return stampedAs(resource, profile) && missing(resource, required[profile]).length === 0;
}

/** The resource as the profile's type, or a ProfileReadError saying why it is not. */
export function asProfiled<U extends ProfileUrl>(resource: Resource, profile: U): ProfileTypes[U] {
  if (isProfiled(resource, profile)) return resource;
  const reference = referenceOf(resource);
  if (!stampedAs(resource, profile)) throw new ProfileReadError(profile, 'unstamped', [{ reference, missing: [] }]);
  throw new ProfileReadError(profile, 'missing', [{ reference, missing: lacks(resource, profile) }]);
}

/**
 * The resources stamped with the profile, or a selected profile deriving from
 * it, each checked and typed; the others are left out. Throws a
 * ProfileReadError when a stamped one lacks what its type requires, with the
 * ones that passed in \`passed\`.
 */
export function pickProfiled<U extends ProfileUrl>(resources: readonly Resource[], profile: U): ProfileTypes[U][] {
  const passed: ProfileTypes[U][] = [];
  const failed: ProfileReadFailure[] = [];
  for (const resource of resources) {
    if (isProfiled(resource, profile)) passed.push(resource);
    else if (stampedAs(resource, profile)) failed.push({ reference: referenceOf(resource), missing: lacks(resource, profile) });
  }
  if (failed.length > 0) throw new ProfileReadError(profile, 'missing', failed, passed);
  return passed;
}

/** A resource as the server returns it, with its id. The same as \`WithId\` in @medplum/core. */
type WithId<T> = T & { id: string };

/**
 * The part of a \`MedplumClient\` the reads use, so the generated code needs no
 * \`@medplum/core\` declarations of its own: a MedplumClient is one.
 */
export interface ProfiledReader {
  readResource(resourceType: ResourceType, id: string): Promise<Resource>;
  readReference(reference: Reference): Promise<Resource>;
  searchResources(resourceType: ResourceType, query: string[][]): Promise<Resource[]>;
}

/**
 * A search query, in any form \`medplum.searchResources\` takes: a string, a
 * URLSearchParams or any other list of pairs, or a record. Typed without
 * URLSearchParams, so the generated code compiles without the DOM lib.
 */
export type ProfiledQuery =
  | string
  | Iterable<readonly string[]>
  | Record<string, string | number | boolean | readonly (string | number | boolean)[] | undefined>;

/**
 * Reads the resource by id, or by reference, and returns it as the profile's
 * type, or rejects with a ProfileReadError when it is not stamped with the
 * profile or lacks what the type requires.
 */
export async function readProfiled<U extends ProfileUrl>(
  medplum: ProfiledReader,
  profile: U,
  idOrReference: string | Reference<Resource & ProfileTypes[U]>,
): Promise<WithId<ProfileTypes[U]>> {
  const resource =
    typeof idOrReference === 'string'
      ? await medplum.readResource(typeOf[profile] as ResourceType, idOrReference)
      : await medplum.readReference(idOrReference);
  return asProfiled(resource, profile) as WithId<ProfileTypes[U]>;
}

// Each returns a subset, which is not the profile's type, or mixes other resources into the results.
const subsets = ['_elements', '_fields', '_summary'];
const includes = ['_include', '_revinclude'];

/**
 * Searches the profile's type for resources stamped with the profile, or a
 * selected profile deriving from it, and returns them typed. One that lacks
 * what the type requires rejects the search with a ProfileReadError holding
 * the rest in \`passed\`. A query asking for a subset or included resources is
 * refused before any request.
 */
export async function searchProfiled<U extends ProfileUrl>(
  medplum: ProfiledReader,
  profile: U,
  query: ProfiledQuery = {},
): Promise<WithId<ProfileTypes[U]>[]> {
  const params = searchParams(query);
  for (const [key] of params) {
    const name = key?.split(':')[0] ?? '';
    if (subsets.includes(name) || includes.includes(name)) throw refusal(profile, name);
  }
  params.push(['_profile', (accepts[profile] ?? [profile]).join(',')]);
  const found = await medplum.searchResources(typeOf[profile] as ResourceType, params);
  return pickProfiled(found, profile) as WithId<ProfileTypes[U]>[];
}

function searchParams(query: ProfiledQuery): string[][] {
  if (typeof query === 'string') {
    return query
      .replace(/^\\?/, '')
      .split('&')
      .filter((pair) => pair !== '')
      .map((pair) => {
        const at = pair.indexOf('=');
        const [key, value] = at === -1 ? [pair, ''] : [pair.slice(0, at), pair.slice(at + 1)];
        return [decode(key), decode(value)];
      });
  }
  const pairs = Symbol.iterator in query ? [...(query as Iterable<readonly string[]>)] : Object.entries(query);
  const params: string[][] = [];
  for (const [key, value] of pairs) {
    for (const v of [value].flat()) if (key !== undefined && v !== undefined) params.push([key, String(v)]);
  }
  return params;
}

// As URLSearchParams decodes: '+' is a space.
const decode = (text: string) => decodeURIComponent(text.replace(/\\+/g, ' '));

function refusal(profile: ProfileUrl, name: string): ProfileReadError {
  const why = subsets.includes(name)
    ? \`a subset is not a \${short(profile)}. Use medplum.searchResources for a subset.\`
    : 'included resources would be mixed into the results. Read them with medplum.searchResources, or with readProfiled from a reference.';
  return new ProfileReadError(profile, 'refused', [], [], \`searchProfiled(\${short(profile)}) refuses \${name}: \${why}\`);
}
`;

/** A table by profile URL, sorted, one entry per line. */
function printTable(name: string, type: string, rows: [string, unknown[]][]): string[] {
  if (rows.length === 0) return [`const ${name}: ${type} = {};`];
  const entries = [...rows].sort(([a], [b]) => a.localeCompare(b));
  return [
    `const ${name}: ${type} = {`,
    ...entries.flatMap(([url, values]) =>
      values.length === 0
        ? [`  ${quote(url)}: [],`]
        : [`  ${quote(url)}: [`, ...values.map((v) => `    ${printValue(v)},`), '  ],'],
    ),
    '};',
  ];
}

/** What a typed read checks for each selected profile, and the checks themselves. */
function printReads(models: ProfileModel[], routing: RoutingTable): string {
  const selected = models.filter((m) => routing.profiles.includes(m.url));
  return [
    `${MARKER}. Do not edit.`,
    "import type { Reference, Resource, ResourceType } from '@medplum/fhirtypes';",
    "import { missing } from './_plumb.js';",
    "import type { ProfileTypes, ProfileUrl } from './_routes.js';",
    '',
    '/**',
    " * The paths each selected profile's type requires beyond @medplum/fhirtypes.",
    ' * A row lists alternatives, any one of which meets it (`missing` in _plumb.ts).',
    ' */',
    ...printTable(
      'required',
      'Record<ProfileUrl, readonly (readonly string[])[]>',
      selected.map((m) => [m.url, m.required]),
    ),
    '',
    '/** The stamps a read accepts as each profile: its own URL, and each selected profile deriving from it. */',
    ...printTable(
      'accepts',
      // Keyed by string, so the lookup still compiles when no profile is selected.
      'Partial<Record<string, readonly string[]>>',
      selected.map((m) => [m.url, routing.accepts[m.url] ?? [m.url]]),
    ),
    '',
    "/** Each profile's resource type. */",
    ...(selected.length === 0
      ? ['const typeOf: Partial<Record<string, ResourceType>> = {};']
      : [
          'const typeOf: Partial<Record<string, ResourceType>> = {',
          ...[...selected]
            .sort((a, b) => a.url.localeCompare(b.url))
            .map((m) => `  ${quote(m.url)}: ${quote(m.sd.type)},`),
          '};',
        ]),
    '',
    READS,
  ].join('\n');
}

function printStamps(stamps: Record<string, string[]>): string {
  const urls = Object.keys(stamps).sort();
  if (urls.length === 0) return '{}';
  return `{\n${urls.map((url) => `  ${quote(url)}: ${printValue(stamps[url])},`).join('\n')}\n}`;
}

const MIGRATIONS = `${MARKER}. Do not edit.
import type { Bundle, Identifier, Resource, ResourceType } from '@medplum/fhirtypes';

/** One RFC 6902 operation. */
export type JsonPatchOperation =
  | { op: 'add'; path: string; value: unknown }
  | { op: 'replace'; path: string; value: unknown }
  | { op: 'test'; path: string; value: unknown }
  | { op: 'remove'; path: string }
  | { op: 'move'; from: string; path: string }
  | { op: 'copy'; from: string; path: string };

/** A data migration: the records it reads, and what it changes in each. */
export interface MigrationDefinition<T extends ResourceType = ResourceType> {
  /** A date and a name, as \`20261006-patient-birthdate\`, so ids sort as written. */
  id: string;
  resourceType: T;
  /** FHIR search parameters, ANDed, narrowing what is read; a modifier goes in the key. */
  search?: Record<string, string>;
  /**
   * The patch for one record, or undefined when it needs nothing, so a run
   * over finished records changes nothing. The record is stale, so it is the
   * base type, not a profile's.
   */
  transform(resource: Extract<Resource, { resourceType: T }>): JsonPatchOperation[] | undefined;
  /** The ids of migrations that must be applied first. */
  dependsOn?: string[];
  description?: string;
}

/** Types a migration; returns it unchanged. */
export function defineMigration<T extends ResourceType>(migration: MigrationDefinition<T>): MigrationDefinition<T> {
  return migration;
}

/** What the runner needs of a client: a MedplumClient fits. */
export interface MigrationClient {
  search(resourceType: ResourceType, query: string): Promise<Bundle>;
  readResource(resourceType: ResourceType, id: string): Promise<Resource>;
  patchResource(
    resourceType: ResourceType,
    id: string,
    operations: JsonPatchOperation[],
    options: { headers: Record<string, string> },
  ): Promise<Resource>;
  executeBot(identifier: Identifier, body: unknown, contentType: string): Promise<unknown>;
}

/** One page of one migration, as \`plumb migrate\` asks the bot to run it. */
export interface MigrationPage {
  /** The migration's id. */
  id: string;
  /** When the run started, as an instant: a record written since is not read again. */
  start: string;
  /** Write the changes; otherwise only count them. */
  write?: boolean;
  /** Records per page: Medplum pages by cursor from 20, and returns at most 1,000. */
  count?: number;
  /** The server's cursor from the previous page; the first page has none. */
  cursor?: string;
  /** Plumb's checker, and what it needs to check the changed records against the selected profiles. */
  forecast?: { checker: Identifier; profiles: string[]; definitions: string };
}

/** The checker's verdict on a page's changed records. */
export interface MigrationForecast {
  /** Records stamped with a selected profile, and of those, the ones failing one. */
  stamped: number;
  failing: number;
  profiles: Record<
    string,
    { checked: number; failing: string[]; reasons: { path: string; message: string; count: number }[] }
  >;
}

/** What one page did: counts, reasons and the versions written. No record's content. */
export interface MigrationPageResult {
  read: number;
  changed: number;
  unchanged: number;
  /** Changed by someone else between the read and the write, twice: left for the next run. */
  conflict: number;
  failed: number;
  reasons: { message: string; count: number }[];
  forecast?: MigrationForecast;
  /** The id and new version of each record written. */
  written: { id: string; versionId: string }[];
  /** The cursor for the next page, absent on the last. */
  next?: string;
}

type Outcome =
  | { kind: 'unchanged' | 'conflict' }
  | { kind: 'failed'; reason: string }
  | { kind: 'changed'; resource: Resource; versionId?: string };

/**
 * The migration bot's handler: runs one page of the migration the input
 * names. Each record is transformed, patched in memory, and with \`write\`,
 * patched on the server against the version read, so a concurrent edit is
 * read again rather than overwritten.
 */
export function handleMigrations(migrations: MigrationDefinition[]) {
  return async (
    medplum: MigrationClient,
    event: { input: MigrationPage },
  ): Promise<MigrationPageResult> => {
    const page = event.input;
    const migration = migrations.find((m) => m.id === page.id);
    if (!migration) throw new Error('This bot has no migration ' + page.id + ': deploy its current build.');
    const bundle = await medplum.search(migration.resourceType, query(migration, page));
    const records = (bundle.entry ?? []).flatMap((e) => (e.resource ? [e.resource] : []));
    const result: MigrationPageResult = {
      read: records.length,
      changed: 0,
      unchanged: 0,
      conflict: 0,
      failed: 0,
      reasons: [],
      written: [],
    };
    const changed: Resource[] = [];
    for (const record of records) {
      const outcome = await migrateRecord(medplum, migration, record, page.write === true);
      result[outcome.kind]++;
      if (outcome.kind === 'failed') {
        const reason = result.reasons.find((r) => r.message === outcome.reason);
        if (reason) reason.count++;
        else result.reasons.push({ message: outcome.reason, count: 1 });
      }
      if (outcome.kind === 'changed') {
        changed.push(outcome.resource);
        if (outcome.versionId) result.written.push({ id: record.id ?? '', versionId: outcome.versionId });
      }
    }
    if (page.forecast && changed.length > 0) {
      const { checker, profiles, definitions } = page.forecast;
      const verdict = (await medplum.executeBot(
        checker,
        { resourceType: migration.resourceType, profiles, definitions, resources: changed },
        'application/json',
      )) as MigrationForecast;
      result.forecast = { stamped: verdict.stamped, failing: verdict.failing, profiles: verdict.profiles };
    }
    const next = /[?&]_cursor=([^&]*)/.exec(bundle.link?.find((l) => l.relation === 'next')?.url ?? '');
    if (next?.[1]) result.next = decodeURIComponent(next[1]);
    return result;
  };
}

/** The migration's search, less what the run has written, in the order Medplum pages by cursor. */
function query(migration: MigrationDefinition, page: MigrationPage): string {
  const count = Math.min(Math.max(page.count ?? 100, 20), 1000);
  const params: [string, string][] = [
    ...Object.entries(migration.search ?? {}),
    ['_lastUpdated', 'lt' + page.start],
    ['_sort', '_lastUpdated'],
    ['_count', String(count)],
  ];
  if (page.cursor) params.push(['_cursor', page.cursor]);
  return params.map(([k, v]) => encodeURIComponent(k) + '=' + encodeURIComponent(v)).join('&');
}

async function migrateRecord(
  medplum: MigrationClient,
  migration: MigrationDefinition,
  stored: Resource,
  write: boolean,
): Promise<Outcome> {
  let record = stored;
  for (let attempt = 0; ; attempt++) {
    const operations = migration.transform(record);
    if (!operations) return { kind: 'unchanged' };
    let resource: Resource;
    try {
      resource = applyJsonPatch(record, operations);
    } catch (err) {
      return { kind: 'failed', reason: 'The patch does not apply: ' + messageOf(err) };
    }
    if (sameJson(resource, record)) return { kind: 'unchanged' };
    if (!write) return { kind: 'changed', resource };
    try {
      const saved = await medplum.patchResource(record.resourceType, record.id ?? '', operations, {
        headers: { 'If-Match': 'W/"' + (record.meta?.versionId ?? '') + '"' },
      });
      return { kind: 'changed', resource, versionId: saved.meta?.versionId ?? '' };
    } catch (err) {
      const outcome = (err as { outcome?: { id?: string } } | undefined)?.outcome;
      if (outcome?.id !== 'precondition-failed') return { kind: 'failed', reason: messageOf(err) };
      if (attempt > 0) return { kind: 'conflict' };
      record = await medplum.readResource(record.resourceType, record.id ?? '');
    }
  }
}

/** Medplum's reason for a refusal, or the error's own message. */
function messageOf(err: unknown): string {
  const issues = (err as { outcome?: { issue?: { details?: { text?: string }; diagnostics?: string }[] } })
    ?.outcome?.issue;
  const text = (issues ?? []).map((i) => i.details?.text ?? i.diagnostics ?? '').filter(Boolean);
  return text.length > 0 ? text.join('; ') : err instanceof Error ? err.message : String(err);
}

/** RFC 6902 applied to a copy; throws when an operation does not apply. */
function applyJsonPatch<T>(target: T, operations: JsonPatchOperation[]): T {
  let doc: unknown = JSON.parse(JSON.stringify(target));
  for (const operation of operations) {
    if (operation.op === 'test') {
      if (!sameJson(valueAt(doc, operation.path), operation.value)) {
        throw new Error('test failed at ' + operation.path);
      }
    } else if (operation.op === 'remove') {
      doc = put(doc, operation.path, undefined, 'remove');
    } else if (operation.op === 'add' || operation.op === 'replace') {
      doc = put(doc, operation.path, clone(operation.value), operation.op);
    } else {
      const value = clone(valueAt(doc, operation.from));
      if (operation.op === 'move') doc = put(doc, operation.from, undefined, 'remove');
      doc = put(doc, operation.path, value, 'add');
    }
  }
  return doc as T;
}

const clone = (value: unknown): unknown => (value === undefined ? undefined : JSON.parse(JSON.stringify(value)));

/** A JSON Pointer's tokens, unescaped. */
const tokens = (pointer: string): string[] =>
  pointer === '' ? [] : pointer.slice(1).split('/').map((t) => t.replaceAll('~1', '/').replaceAll('~0', '~'));

function valueAt(doc: unknown, pointer: string): unknown {
  let value = doc;
  for (const token of tokens(pointer)) {
    if (typeof value !== 'object' || value === null || !Object.hasOwn(value, token)) {
      throw new Error('nothing at ' + pointer);
    }
    value = (value as Record<string, unknown>)[token];
  }
  return value;
}

/** Adds, replaces or removes the value at a pointer, returning the document. */
function put(doc: unknown, pointer: string, value: unknown, op: 'add' | 'replace' | 'remove'): unknown {
  const path = tokens(pointer);
  const last = path.pop();
  if (last === undefined) {
    if (op === 'remove') throw new Error('cannot remove the whole record');
    return value;
  }
  const parent = valueAt(doc, path.length === 0 ? '' : '/' + path.map(escape).join('/'));
  if (Array.isArray(parent)) {
    const index = last === '-' && op === 'add' ? parent.length : Number(last);
    const end = op === 'add' ? parent.length : parent.length - 1;
    if (!/^(0|[1-9][0-9]*|-)$/.test(last) || !(index >= 0 && index <= end)) {
      throw new Error('no index ' + last + ' at ' + pointer);
    }
    parent.splice(index, op === 'add' ? 0 : 1, ...(op === 'remove' ? [] : [value]));
  } else if (typeof parent === 'object' && parent !== null) {
    const record = parent as Record<string, unknown>;
    if (op !== 'add' && !Object.hasOwn(record, last)) throw new Error('nothing at ' + pointer);
    if (op === 'remove') delete record[last];
    else record[last] = value;
  } else {
    throw new Error('nothing to change at ' + pointer);
  }
  return doc;
}

const escape = (token: string) => token.replaceAll('~', '~0').replaceAll('/', '~1');

/** Whether two JSON values are equal, whatever the order of their keys. */
function sameJson(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (typeof a !== 'object' || typeof b !== 'object' || a === null || b === null) return false;
  if (Array.isArray(a) !== Array.isArray(b)) return false;
  const keys = Object.keys(a);
  return (
    keys.length === Object.keys(b).length &&
    keys.every((k) => Object.hasOwn(b, k) && sameJson((a as Record<string, unknown>)[k], (b as Record<string, unknown>)[k]))
  );
}
`;

/**
 * `_migrator.ts`, the migration bot's handler: every module the config lists,
 * by its import path from `out`. Not exported from the index, since the
 * modules import the index themselves.
 */
function printMigrator(modules: string[]): string {
  const imports = modules.map((path, i) => `import m${i} from ${quote(path)};`);
  const list = modules.map((_, i) => `m${i}`).join(', ');
  return `${MARKER}. Do not edit.
import { handleMigrations } from './_migrations.js';
${imports.join('\n')}${imports.length > 0 ? '\n' : ''}
/** The migration bot's handler: its entry exports it, as \`export { handler } from './_migrator.js'\`. */
export const handler = handleMigrations([${list}]);
`;
}

/**
 * Every file Plumb writes to `out`: one per profile and per Questionnaire in
 * `content`, the index, the shared helpers, the routes and the reads, the
 * operation contracts when the config lists `operations`, and the typed bot
 * handlers, printed by `printBots`, when it declares `bots`.
 */
export function printFiles(
  models: ProfileModel[],
  hashOf: (model: ProfileModel) => string,
  routing: RoutingTable = { routes: {}, profiles: [], stamps: {}, managed: [], accepts: {} },
  questionnaires: { name: string; file: string }[] = [],
  operations: string[] = [],
  bots?: string,
  migrations?: string[],
): Map<string, string> {
  const owners: Owners = new Map(
    models.flatMap((m) => m.decls.map((d): [string, string] => [d.name, m.typeName])),
  );
  const files = new Map<string, string>();
  for (const model of models) {
    files.set(`${model.typeName}.ts`, printProfile(model, hashOf(model), owners));
  }
  const index = new FileBuilder('  ', false);
  index.appendNoWrap(`${MARKER}. Do not edit.`);
  index.appendNoWrap("export type { Require } from './_plumb.js';");
  index.appendNoWrap(
    "export { createProfiled, type ProfiledClient, type ProfileTypes, type ProfileUrl, RoutingError, route, stampProfiled, updateProfiled } from './_routes.js';",
  );
  index.appendNoWrap(
    "export { asProfiled, isProfiled, pickProfiled, type ProfiledQuery, type ProfiledReader, ProfileReadError, type ProfileReadFailure, readProfiled, searchProfiled } from './_reads.js';",
  );
  if (operations.length > 0) {
    index.appendNoWrap(
      "export { callOperation, defineOperation, handleOperation, type OperationClient, type OperationContract, OperationError, type OperationSide, type SideInput, type SideOutput, type StandardSchemaV1 } from './_operations.js';",
    );
    files.set('_operations.ts', OPERATIONS);
  }
  if (migrations) {
    index.appendNoWrap(
      "export { defineMigration, handleMigrations, type JsonPatchOperation, type MigrationClient, type MigrationDefinition, type MigrationForecast, type MigrationPage, type MigrationPageResult } from './_migrations.js';",
    );
    files.set('_migrations.ts', MIGRATIONS);
    files.set('_migrator.ts', printMigrator(migrations));
  }
  if (bots) {
    index.appendNoWrap(
      "export { type BotInputs, type BotSecrets, defineBot, type PlumbBotEvent } from './_bots.js';",
    );
    files.set('_bots.ts', bots);
  }
  for (const q of questionnaires) files.set(`${q.name}Answers.ts`, q.file);
  const names = [
    ...models.map((m) => m.typeName),
    ...questionnaires.map((q) => `${q.name}Answers`),
  ];
  for (const name of names.sort()) {
    index.appendNoWrap(`export * from './${name}.js';`);
  }
  files.set('index.ts', index.toString());
  files.set('_plumb.ts', questionnaires.length > 0 ? HELPERS + ANSWERS : HELPERS);
  files.set('_routes.ts', printRoutes(routing, new Map(models.map((m) => [m.url, m.typeName]))));
  files.set('_reads.ts', printReads(models, routing));
  return files;
}
