// SPDX-FileCopyrightText: Copyright Balance Hormone Center and Plumb contributors
// SPDX-License-Identifier: Apache-2.0

// Print: every formatting rule lives here. A pure function from the type
// model to text, with no FHIR knowledge.
import { FileBuilder, wordWrap } from '@medplum/core';
import type { Field, Helper, ProfileModel, TypeExpr } from './transform.js';

/** The first line of every file Plumb writes, so it can tell its files from others. */
export const MARKER = '// Generated by Plumb';
const WIDTH = 100;

const HELPERS = `${MARKER}. Do not edit.
/** \`T\` with the keys \`K\` required, and never \`undefined\`. */
export type Require<T, K extends keyof T> = Omit<T, K> & { [P in K]-?: NonNullable<T[P]> };

/** \`Omit\` over each member of a union, so an exactly-one-of type stays one. */
export type OmitEach<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never;

/**
 * Whether \`value\` holds everything in \`pattern\`, as FHIR matches a slice's
 * discriminator: an array in the pattern means each entry appears somewhere, and
 * a single pattern against an array is met by any entry.
 */
export function matches(value: unknown, pattern: unknown): boolean {
  if (Array.isArray(value) && !Array.isArray(pattern)) return value.some((v) => matches(v, pattern));
  if (Array.isArray(pattern)) {
    return Array.isArray(value) && pattern.every((p) => value.some((v) => matches(v, p)));
  }
  if (pattern !== null && typeof pattern === 'object') {
    if (value === null || typeof value !== 'object') return false;
    const record = value as Record<string, unknown>;
    return Object.entries(pattern).every(([key, p]) => matches(record[key], p));
  }
  return value === pattern;
}
`;

const quote = (text: string) => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const indentRest = (text: string, by: string) => text.replaceAll('\n', `\n${by}`);
const needsParens = (t: TypeExpr) => t.kind === 'union' || t.kind === 'narrow';
const paren = (t: TypeExpr) => (needsParens(t) ? `(${printExpr(t)})` : printExpr(t));

function docLines(text: string[], width: number): string[] {
  const body = text.flatMap((line) =>
    line ? wordWrap(line.replaceAll('*/', '*\\/'), width) : [''],
  );
  return ['/**', ...body.map((line) => (line ? ` * ${line}` : ' *')), ' */'];
}

function printField(field: Field): string {
  const line = `${field.name}${field.optional ? '?' : ''}: ${printExpr(field.type)};`;
  if (!field.doc) return line;
  const doc = `/** ${field.doc.replaceAll('*/', '*\\/')} */`;
  const lines = doc.length <= WIDTH - 2 ? [doc] : docLines([field.doc], WIDTH - 5);
  return [...lines, line].join('\n');
}

function block(fields: Field[]): string {
  if (fields.length === 0) return '{}';
  return `{\n${fields.map((f) => `  ${indentRest(printField(f), '  ')}`).join('\n')}\n}`;
}

/** A type expression as TypeScript; nested lines are indented relative to the first. */
export function printExpr(t: TypeExpr): string {
  switch (t.kind) {
    case 'ref':
      return t.args ? `${t.name}<${t.args.map(printExpr).join(', ')}>` : t.name;
    case 'primitive':
      return t.name;
    case 'index':
      return `NonNullable<${t.base}[${quote(t.key)}]>`;
    case 'literal':
      return typeof t.value === 'string' ? quote(t.value) : String(t.value);
    case 'array':
      return `${paren(t.of)}[]`;
    case 'tuple':
      return `[${t.of.map(printExpr).join(', ')}]`;
    case 'optional':
      return `${paren(t.of)}?`;
    case 'rest':
      return `...${paren(t.of)}[]`;
    case 'union':
      return t.of.map(paren).join(' | ');
    case 'object':
      return block(t.fields);
    case 'require':
      return `Require<${printExpr(t.base)}, ${t.keys.map(quote).join(' | ')}>`;
    case 'never':
      return 'never';
    case 'narrow': {
      const base = printExpr(t.base);
      const keys = t.omit.map(quote);
      const inline = `Omit<${base}, ${keys.join(' | ')}>`;
      // A long list goes one key per line, so the file stays readable.
      const omitted =
        keys.length === 0
          ? base
          : inline.length <= 80
            ? inline
            : `Omit<\n  ${base},\n${keys.map((k) => `  | ${k}`).join('\n')}\n>`;
      const groups = (t.oneOf ?? []).map(
        (branches) =>
          ` & (\n${branches.map((b) => `  | ${indentRest(block(b), '    ')}`).join('\n')}\n)`,
      );
      return `${omitted} & ${block(t.fields)}${groups.join('')}`;
    }
  }
}

/** Every type name an expression refers to. */
function names(t: TypeExpr, into: Set<string>): Set<string> {
  switch (t.kind) {
    case 'ref':
      into.add(t.name);
      for (const arg of t.args ?? []) names(arg, into);
      break;
    case 'index':
      into.add(t.base);
      break;
    case 'array':
    case 'optional':
    case 'rest':
      names(t.of, into);
      break;
    case 'tuple':
    case 'union':
      for (const item of t.of) names(item, into);
      break;
    case 'object':
      for (const f of t.fields) names(f.type, into);
      break;
    case 'require':
      into.add('Require');
      names(t.base, into);
      break;
    case 'narrow':
      names(t.base, into);
      for (const f of [...t.fields, ...(t.oneOf ?? []).flat(2)]) names(f.type, into);
      break;
  }
  return into;
}

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

/** A JSON value as a TypeScript expression. */
function printValue(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(printValue).join(', ')}]`;
  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value).map(
      ([key, v]) => `${IDENTIFIER.test(key) ? key : quote(key)}: ${printValue(v)}`,
    );
    return `{ ${entries.join(', ')} }`;
  }
  return typeof value === 'string' ? quote(value) : String(value);
}

function printHelper(h: Helper): string[] {
  const keys = Object.keys(h.values);
  if (h.kind === 'build') {
    return [
      `  /** A ${h.element} entry in the ${h.slice} slice, with ${keys.join(' and ')} filled in. */`,
      `  ${h.name}: (entry: OmitEach<${h.shape}, ${keys.map(quote).join(' | ')}>): ${h.shape} => ({`,
      '    ...entry,',
      ...keys.map((key) => `    ${key}: ${printValue(h.values[key])},`),
      '  }),',
    ];
  }
  return [
    `  /** The first ${h.element} entry in the ${h.slice} slice, if there is one. */`,
    `  ${h.name}: (parent: { ${h.element}?: ${h.item}[] }): ${h.shape} | undefined =>`,
    `    parent.${h.element}?.find((e): e is ${h.shape} => matches(e, ${printValue(h.values)})),`,
  ];
}

function printProfile(model: ProfileModel, hash: string): string {
  const b = new FileBuilder('  ', false);
  const version = model.version ? `|${model.version}` : '';
  b.appendNoWrap(`${MARKER} from ${model.url}${version}. Do not edit.`);
  b.appendNoWrap(`// Source: ${model.source} ${hash}`);
  const used = new Set<string>();
  for (const d of model.decls) names(d.type, used);
  for (const h of model.helpers) used.add(h.item);
  const local = new Set(model.decls.map((d) => d.name));
  const fhir = [...used].filter((n) => !local.has(n) && n !== 'Require').sort();
  if (fhir.length > 0)
    b.appendNoWrap(`import type { ${fhir.join(', ')} } from '@medplum/fhirtypes';`);
  const plumb = [
    ...(model.helpers.length > 0 ? ['matches'] : []),
    ...(model.helpers.some((h) => h.kind === 'build') ? ['type OmitEach'] : []),
    ...(used.has('Require') ? ['type Require'] : []),
  ];
  if (plumb.length > 0) b.appendNoWrap(`import { ${plumb.join(', ')} } from './_plumb.js';`);
  b.newLine();
  b.appendNoWrap(`/** The canonical URL of ${model.typeName}. */`);
  b.appendNoWrap(`export const ${model.typeName}ProfileUrl = ${quote(model.url)};`);
  model.decls.forEach((d, i) => {
    b.newLine();
    if (i === 0) for (const line of docLines(model.doc, WIDTH - 3)) b.appendNoWrap(line);
    for (const line of `export type ${d.name} = ${printExpr(d.type)};`.split('\n'))
      b.appendNoWrap(line);
  });
  if (model.helpers.length > 0) {
    b.newLine();
    b.appendNoWrap(`/** Builders and readers for the slices of ${model.typeName}. */`);
    b.appendNoWrap(`export const ${model.typeName} = {`);
    for (const line of model.helpers.flatMap(printHelper)) b.appendNoWrap(line);
    b.appendNoWrap('};');
  }
  return b.toString();
}

/** Every file Plumb writes to `out`: one per profile, the index and the shared helpers. */
export function printFiles(
  models: ProfileModel[],
  hashOf: (model: ProfileModel) => string,
): Map<string, string> {
  const files = new Map<string, string>();
  for (const model of models) files.set(`${model.typeName}.ts`, printProfile(model, hashOf(model)));
  const index = new FileBuilder('  ', false);
  index.appendNoWrap(`${MARKER}. Do not edit.`);
  index.appendNoWrap("export type { Require } from './_plumb.js';");
  for (const name of models.map((m) => m.typeName).sort()) {
    index.appendNoWrap(`export * from './${name}.js';`);
  }
  files.set('index.ts', index.toString());
  files.set('_plumb.ts', HELPERS);
  return files;
}
