// SPDX-FileCopyrightText: Copyright Balance Hormone Center and Plumb contributors
// SPDX-License-Identifier: Apache-2.0
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { MARKER } from './print.js';

interface WriteIssue {
  code: 'foreign-file';
  message: string;
  file: string;
}

export interface WriteResult {
  ok: boolean;
  written: string[];
  removed: string[];
  errors: WriteIssue[];
}

/** A generated file that differs from what the committed folder holds. */
export interface Stale {
  file: string;
  problem: 'stale' | 'missing' | 'extra';
  /** What changed, read from the file headers. */
  cause: string;
}

/** The folder's files, or the files in it Plumb did not write. */
function inspect(out: string): { existing: string[]; errors: WriteIssue[] } {
  const existing = existsSync(out) ? readdirSync(out).sort() : [];
  const ours = (name: string) => {
    const path = join(out, name);
    return statSync(path).isFile() && readFileSync(path, 'utf8').startsWith(MARKER);
  };
  const errors = existing
    .filter((name) => !ours(name))
    .map((file) => ({
      code: 'foreign-file' as const,
      file,
      message: `${join(out, file)} was not written by Plumb. Plumb owns ${out}; move the file elsewhere.`,
    }));
  return { existing, errors };
}

/**
 * Makes `out` hold exactly `files`. Plumb owns the folder: it removes its own
 * files that are no longer generated, and touches nothing if the folder holds
 * anything it did not write.
 */
export function writeFiles(out: string, files: Map<string, string>): WriteResult {
  const { existing, errors } = inspect(out);
  if (errors.length > 0) return { ok: false, written: [], removed: [], errors };

  mkdirSync(out, { recursive: true });
  const removed = existing.filter((name) => !files.has(name));
  for (const name of removed) rmSync(join(out, name));
  const written: string[] = [];
  for (const [name, text] of [...files].sort(([a], [b]) => (a < b ? -1 : 1))) {
    const path = join(out, name);
    if (existing.includes(name) && readFileSync(path, 'utf8') === text) continue;
    writeFileSync(path, text);
    written.push(name);
  }
  return { ok: true, written, removed, errors: [] };
}

/** Compares `files` with `out`, byte for byte, writing nothing. */
export function compareFiles(
  out: string,
  files: Map<string, string>,
): { stale: Stale[]; errors: WriteIssue[] } {
  const { existing, errors } = inspect(out);
  if (errors.length > 0) return { stale: [], errors };
  const stale: Stale[] = [];
  for (const [file, text] of [...files].sort(([a], [b]) => (a < b ? -1 : 1))) {
    if (!existing.includes(file)) {
      stale.push({ file, problem: 'missing', cause: `${describe(text)} has not been generated.` });
      continue;
    }
    const actual = readFileSync(join(out, file), 'utf8');
    if (actual !== text) stale.push({ file, problem: 'stale', cause: explain(actual, text) });
  }
  for (const file of existing.filter((name) => !files.has(name))) {
    const text = readFileSync(join(out, file), 'utf8');
    stale.push({ file, problem: 'extra', cause: `${describe(text)} is no longer selected.` });
  }
  return { stale, errors: [] };
}

interface Header {
  url?: string;
  version?: string;
  source?: string;
}

/** A generated file's first two lines: its profile and version, and its source and hash. */
function header(text: string): Header {
  const [first = '', second = ''] = text.split('\n');
  const from = /^\/\/ Generated by Plumb from (.+)\. Do not edit\.$/.exec(first)?.[1];
  const at = from?.lastIndexOf('|') ?? -1;
  return {
    url: from && at > 0 ? from.slice(0, at) : from,
    version: from && at > 0 ? from.slice(at + 1) : undefined,
    source: /^\/\/ Source: (.+)$/.exec(second)?.[1],
  };
}

function describe(text: string): string {
  const url = header(text).url;
  return url ? `The profile ${url}` : 'This file';
}

function explain(actual: string, expected: string): string {
  const was = header(actual);
  const now = header(expected);
  if (was.url && was.url === now.url && was.version !== now.version) {
    return `${now.url} changed version: ${was.version ?? 'none'} → ${now.version ?? 'none'}.`;
  }
  if (was.source !== now.source) {
    return `${describe(expected)}'s source changed: ${was.source} → ${now.source}.`;
  }
  return 'The regenerated file differs: edited by hand, or generated by another version of Plumb or Medplum.';
}
